[tools]
node = "24.12.0"
gemini = "latest"
deno = "2.7.14"
neovim = "latest"
fzf = "latest"
pnpm = "10.33.4"
uv = "0.11.11"
"aqua:cli/cli" = "2.92.0"

"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@openai/codex" = "latest"
"npm:@playwright/cli" = "latest"

"pipx:beko-translate" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
